// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpvnnudfbgrexwbafwki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdm5udWRmYmdyZXh3YmFmd2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjA4ODAsImV4cCI6MjA2NzM5Njg4MH0.Xnkagk2Tchd5Jxq4fsi8o7lMXuGAl7FICL-Y94FuG8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});